name: Download File

on:
  workflow_dispatch:
    inputs:
      url:
        description: "File URL"
        required: true
        type: string
      release_name:
        description: "title"
        required: true
        type: string

jobs:
  download_and_upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Install aria2
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2

      - name: Download file with progress
        run: |
          aria2c \
            --summary-interval=5 \
            --file-allocation=none \
            -x16 -s16 -k1M \
            --console-log-level=warn \
            "${{ inputs.url }}"

      - name: Detect downloaded filename
        id: file
        run: |
          FILE=$(ls -t | head -n1)
          echo "filename=$FILE" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ github.run_number }}
          name: ${{ github.event.inputs.release_name }}
          files: ${{ steps.file.outputs.filename }}
