name: Download YouTube Video

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: "YouTube URL"
        required: true

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg nodejs
          python3 -m pip install --upgrade pip
          pip install -U yt-dlp

      - name: Write cookies
        run: |
          echo "${{ secrets.YT_COOKIES }}" > cookies.txt

      - name: Download video (MP4)
        run: |
          yt-dlp \
            --cookies cookies.txt \
            --js-runtimes node \
            --remote-components ejs:github \
            -f "bv*+ba/b" \
            --merge-output-format mp4 \
            -o "video.%(ext)s" \
            "${{ github.event.inputs.youtube_url }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: youtube-video
          path: video.mp4
