name: Download file

on:
  workflow_dispatch:
    inputs:
      url:
        description: "File URL"
        required: true

jobs:
  download_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Install aria2
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2

      - name: Download file with progress
        run: |
          aria2c \
            --summary-interval=5 \
            --file-allocation=none \
            -x16 -s16 -k1M \
            --console-log-level=warn \
            "${{ inputs.url }}"

      - name: Detect downloaded filename
        id: file
        run: |
          FILE=$(ls -t | head -n1)
          echo "filename=$FILE" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ steps.file.outputs.filename }}
          path: ${{ steps.file.outputs.filename }}
